### ISSUE TITLE
About painting and camera number.

### ISSUE THREAD

**Issue by EliomEssaim** [Song-Jingyu/PointPainting#23]
I run codes in painting.py. I found it needs at least two cameras to complete the painting process. According to the paper, there seem no limits on the number of cameras. 
Now, I got a dataset that only uses one camera. (it mimics the Kitti dataset)
I try to copy image_2 to image_3.
But it does not work.
When I run the test.py, I got a result that all metrics are 0.

Could you give me some advice on how to revise the code in painting.py to generate a normal result?

**Comment by EliomEssaim** [comment]
![QQ截图20220705220635](https://user-images.githubusercontent.com/31036659/177347889-7812edd4-c8d8-4b2f-825b-b50585f9b8f8.png)
I got  results like this, using demo.py.
It seems that there are no problems with painting, but I have no idea why I get such a terrible prediction. （The model works well on Kitti dataset）
Could you give me some advice?

**Comment by Song-Jingyu** [comment]
It seems your dataset has been changed, have you re-trained the model?

**Comment by G-hx** [comment]
I have the same problem, my solution is to download image3 in kitti dataset.Do you copy image2 to image3 or download image3 in the kitti dataset?

**Comment by EliomEssaim** [comment]
I copy image2 to image3.
The scenes recorded in my dataset are different from the Kitti dataset. If I download image3 from Kitti, it will result in a mismatch between image2 to image3. @G-hx

**Comment by G-hx** [comment]
The dataset I use for training is the kitti dataset. In the kitti dataset, image2 and image3 have parallax. So I am also very doubtful about whether image3 needs to copy image2 or use image3 in the kitti dataset. @[EliomEssaim]

**Comment by EliomEssaim** [comment]
I solved it by normalizing lidar point cloud reflectivity .

**Comment by Song-Jingyu** [comment]
Glad to hear that you finally solved your problem!

**Comment by Yuepengxin** [comment]
> ![QQ截图20220705220635](https://user-images.githubusercontent.com/31036659/177347889-7812edd4-c8d8-4b2f-825b-b50585f9b8f8.png) I got results like this, using demo.py. It seems that there are no problems with painting, but I have no idea why I get such a terrible prediction. （The model works well on Kitti dataset） Could you give me some advice?




Hello, thanks for your excellent work  about Pointpainting.I recently tried to run the Pointpainting in the environment of ubuntu18.04 and python3.7.The previous work has been completed, but I encountered difficulties in the final visualization step.I see that you have already visualized the point cloud, and it is still a color point cloud, so I would like to ask you some questions about the final visualization of this project.
The visualizer I use is Mayavi by the original author. However, due to the problem of version or some feature packs, many methods have not been successful:
![image](https://user-images.githubusercontent.com/103159809/220542328-3fa55d98-90d5-4786-9368-92749adb7bdf.png)

So can you tell me, what visualizer are you using? How did you configure and install it and link to this project?Looking forward to your reply.Your suggestion would be greatly appreciated.Finally, thank you again for reading and helping.
