### ISSUE TITLE
Integration into OpenPCDet

### ISSUE THREAD

**Issue by MartinHahner** [Song-Jingyu/PointPainting#4]
**Nice work!** :clap: 

@Song-Jingyu
How much effort do you estimate to integrate your code into the official OpenPCDet repository?
It would be great if you could create a pull-request that merges your modifications/additions into the official OpenPCDet repository!

**Comment by Song-Jingyu** [comment]
Hi Martin,

It is my honor to receive your comment! I do remember you are one of OpenPCDet contributors! I think most of the efforts may lie in integrating it in offcial OpenPCDet without affecting its original functions. I think it may take me a couple of days as I am not very familiar with git operations like how to add pull-request etc. If you have time and are interested, I think we can discuss on an elegant way to do this (like how to add the segmentation module into the OpenPCDet). Thanks so much for your comment!

Best,
Jingyu

**Comment by MartinHahner** [comment]
Hi Jingyu, 

it is true that I contributed (small fixes) to OpenPCDet, but I am nowhere near to be a maintainer.
I have therefore created an "[issue](https://github.com/open-mmlab/OpenPCDet/issues/539)" in OpenPCDet asking the maintainers for further advice.

To create a pull request, the easiest way is to fork OpenPCDet at its current state, then add your changes and github will then usually automatically ask you on the website of your fork if you want to create a pull request. 

[Here](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) is also a documentation if github does not ask you automatically.  

I think it is best to keep track of the integration now in the OpenPCDet issue, so I will close this issue here.

Greets, Martin

**Comment by sshaoshuai** [comment]
Hi Jingyu, 

Excellent works for your implementation of PointPainting! 

Because PointPainting only modifies the input of LiDAR-only models, I think it should be better to consider the segmentation models as an external library, instead of integrating the segmentation models to OpenPCDet.

I appreciate your potential contributions to OpenPCDet on the following things:

1. Support the data loading of painted point clouds, I guess you just need to add some options and some configs to load painted point clouds or to create painted gt_database as follows: 

https://github.com/Song-Jingyu/PointPainting/blob/35c7d9acfa9d18fd8071caf824a1bd8ab9603018/detector/pcdet/datasets/kitti/painted_kitti_dataset.py#L72-L75

https://github.com/Song-Jingyu/PointPainting/blob/35c7d9acfa9d18fd8071caf824a1bd8ab9603018/detector/pcdet/datasets/kitti/painted_kitti_dataset.py#L227

2. Provide some PointPainting baselines and models on the RAEDME.md 
3. Write some documention to introduce how to run PointPainting with OpenPCDet and your repo. 


Finally I think the future pipeline to run PaintPainting could be as follows: 
1. Run the segmentation modules on your repo to generate painted point clouds on the specifying folder of OpenPCDet, like data/kitti/xxx
2. Run OpenPCDet with pointpainting configs to load painted point clouds for 3D object detection. 

Another suggession: 
If you have contributed the above things to OpenPCDet, then I think you could directly consider the latest OpenPCDet as a submodule of your repo, then in that way your repo could keep the OpenPCDet repo up-to-date in the future.
The submodule could be used like somthing as here: https://github.com/sshaoshuai/PointRCNN. 

Thank you!

Best,
Shaoshuai

**Comment by Song-Jingyu** [comment]
> Hi Jingyu,
> 
> Excellent works for your implementation of PointPainting!
> 
> Because PointPainting only modifies the input of LiDAR-only models, I think it should be better to consider the segmentation models as an external library, instead of integrating the segmentation models to OpenPCDet.
> 
> I appreciate your potential contributions to OpenPCDet on the following things:
> 
> 1. Support the data loading of painted point clouds, I guess you just need to add some options and some configs to load painted point clouds or to create painted gt_database as follows:
> 
> https://github.com/Song-Jingyu/PointPainting/blob/35c7d9acfa9d18fd8071caf824a1bd8ab9603018/detector/pcdet/datasets/kitti/painted_kitti_dataset.py#L72-L75
> 
> https://github.com/Song-Jingyu/PointPainting/blob/35c7d9acfa9d18fd8071caf824a1bd8ab9603018/detector/pcdet/datasets/kitti/painted_kitti_dataset.py#L227
> 
> 1. Provide some PointPainting baselines and models on the RAEDME.md
> 2. Write some documention to introduce how to run PointPainting with OpenPCDet and your repo.
> 
> Finally I think the future pipeline to run PaintPainting could be as follows:
> 
> 1. Run the segmentation modules on your repo to generate painted point clouds on the specifying folder of OpenPCDet, like data/kitti/xxx
> 2. Run OpenPCDet with pointpainting configs to load painted point clouds for 3D object detection.
> 
> Another suggession:
> If you have contributed the above things to OpenPCDet, then I think you could directly consider the latest OpenPCDet as a submodule of your repo, then in that way your repo could keep the OpenPCDet repo up-to-date in the future.
> The submodule could be used like somthing as here: https://github.com/sshaoshuai/PointRCNN.
> 
> Thank you!
> 
> Best,
> Shaoshuai

Thanks so much @sshaoshuai I was quite bust with my personal business these days, I will start working on the integration as soon as I get some free time. Thanks so much again!

**Comment by Soodep** [comment]
Is the inegration done? I am planning to use openpcdet and pointpainting so I was just wondering if the integration was done or not.
